name: CD - Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker"]
    types: [ "completed" ]

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    
    defaults:
      run:
        # 1. Voltamos para o 'powershell' (padrão do Windows)
        shell: powershell

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set vars
        id: vars
        run: |
          echo "IMAGE=apolinarioo/kubernets_trabalho" >> $env:GITHUB_OUTPUT
          $SHA_FULL = "${{ github.event.workflow_run.head_sha }}"
          $TAG_SHA = $SHA_FULL.Substring(0, 7)
          echo "TAG_SHA=$TAG_SHA" >> $env:GITHUB_OUTPUT
          echo "NAMESPACE=${{ secrets.K8S_NAMESPACE || 'default' }}" >> $env:GITHUB_OUTPUT

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      # --- INÍCIO DA CORREÇÃO ---
      - name: Build Nginx image inside Minikube
        run: |
          # 2. Adicionado '--shell=powershell' para forçar a saída correta
          minikube -p minikube docker-env --shell=powershell | invoke-expression
          docker build -t nginx-trabalho:latest ./nginx
      # --- FIM DA CORREÇÃO ---
          
      - name: Create namespace if not exists
        run: |
          kubectl create ns ${{ steps.vars.outputs.NAMESPACE }} -ErrorAction SilentlyContinue

      - name: Apply base manifests (Service, Prometheus, Grafana, Nginx)
        run: |
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/service.yaml -ErrorAction SilentlyContinue
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/prometheus-config.yaml -ErrorAction SilentlyContinue
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/prometheus-deployment.yaml -ErrorAction SilentlyContinue
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/grafana-deployment.yaml -ErrorAction SilentlyContinue
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/grafana-service.yaml -ErrorAction SilentlyContinue
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/nginx-deployment.yaml -ErrorAction SilentlyContinue
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/nginx-service.yaml -ErrorAction SilentlyContinue

      - name: Apply app deployment
        run: |
          kubectl apply -n ${{ steps.vars.outputs.NAMESPACE }} -f k8s/deployment.yaml

      - name: Set image to new tag
        run: |
          kubectl set image deployment/trabalho trabalho=${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG_SHA }} -n ${{ steps.vars.outputs.NAMESPACE }}

      - name: Wait rollout
        run: |
          kubectl rollout status deployment/trabalho -n ${{ steps.vars.outputs.NAMESPACE }} --timeout=120s